### PR TITLE
Extend ldap.Error to include reference to response

### PR DESCRIPTION
**Pull request by johnweldon**
Address #271

### CODE REVIEW

**Comment by blakewedwards** [comment]
I'm hesitant about an interface where the method of processing results changes substantially when a limit is set on the request. In comparison
```
for v in `select x from y`
  // process v  
```
and
```
for v in `select x from y limit 1000`
  // process v  
```
don't seem like they should require significant changes to process results.

Another comparison is https://golang.org/pkg/io/#LimitReader
This will return io.EOF when the limit is reached but the buffer is still populated and n is still the number of bytes read

**Comment by johnweldon** [comment]
I was thinking about that.  I think we should add a new `Search` method that wraps this transparently, rather than modifying an existing `Search` method. 
I'll update this PR with what I'm thinking about that.

**Comment by johnweldon** [comment]
You're right - it's even more inelegant to try to handle this with the packet on the error object.

I concede fully :D 

I'll keep my addition of the `Packet` in the error as potentially-useful/low-cost addition.

**Comment by blakewedwards** [comment]
lgtm and my tests are passing. Thanks for the quick update on this

**Pull request merged**
