### PR TITLE
IsErrorAnyOf should match the given result code even if the error is wrapped

### PR DESCRIPTION
**Pull request by t2y**
This might break compatibility, but I guess that most developers want this behavior. What do you think?

### CODE REVIEW

**Comment by t2y** [comment]
CI job failed, but it is another issue instead of this PR.

https://github.com/go-ldap/ldap/actions/runs/6781841980/job/18432888679#step:5:67

**Comment by t2y** [comment]
> --- FAIL: FuzzParseDN (0.00s)
> --- FAIL: FuzzDecodeEscapedSymbols (0.00s)
> --- FAIL: FuzzEscapeDN (0.00s)
> --- FAIL: FuzzParseDN (0.00s)
> --- FAIL: FuzzDecodeEscapedSymbols (0.00s)
> --- FAIL: FuzzEscapeDN (0.00s)
> --- FAIL: FuzzParseDN (0.00s)
> --- FAIL: FuzzDecodeEscapedSymbols (0.00s)
> --- FAIL: FuzzEscapeDN (0.00s)

https://github.com/go-ldap/ldap/actions/runs/6781841980/job/18726095280?pr=471

**Comment by t2y** [comment]
Still, three jobs are left. Could you re-run or permit me to run CI jobs?

**Comment by t2y** [comment]
I will rebase from #473 if it would be merged first. Then, CI jobs will be passed.

**Comment by t2y** [comment]
As intended.

**Comment by johnweldon** [comment]
Thank you again @t2y

**Pull request merged**
