### PR TITLE
Handling nil errors on addDefaultLDAPResponseDescriptions

### PR DESCRIPTION
**Pull request by jespino**
This is for solve the same problem solved here: #217 but following (more or less) the suggestions provided in the PR comments.

### CODE REVIEW

**Comment by stefanmcshane** [comment]
@jespino there are some errors with this. If you can commit the changes to /v3 folder for go.mod support, and fix the conflicts, we can look at getting this merged.

Thanks

**Comment by jespino** [comment]
@stefanmcshane I moved the changes to the `v3` folder, I don't know if you want to keep the other changes outside too. Let me know and I can copy it again to the `ldap.go` file in the root directory.

**Comment by jespino** [comment]
@johnweldon Any suggestion to get this in? Is any change needed?

**Comment by johnweldon** [comment]
Thanks @jespino - yeah, it's a pain, but we should keep the changes in both the root and the v3 folder, generally speaking.

**Comment by jespino** [comment]
Yes, no problem @johnweldon. Done! :)

**Pull request merged**
