### PR TITLE
Add Entry Unmarshal

### PR DESCRIPTION
**Pull request by clementblaise**
Add a decoding feature to Result Entry

### CODE REVIEW

**Comment by stefanmcshane** [comment]
Hi @clementblaise, 
Apologies for the slow reply. Can you apply the changes to the relevant files in v3/ folder as well to ensure modules support?
Ill get this merged this weekend if possible.
Thanks,
Stefan

**Comment by clementblaise** [comment]
Hello @stefanmcshane, I have update the v3 folder

**Comment by cpuschma** [comment]
@clementblaise Thank you for this PR, I really like this feature! Maybe we can even add an unmarshal function for SearchResult in the future :)

Can you update your branch so we can get the conflict resolved and this PR merged? ☺️

**Comment by 4xoc** [comment]
When could we get this PR merged? This is very nice feature missing for a long time imho and I would very much like to see this part of this library.

**Comment by cpuschma** [comment]
There are three things that still slightly bug me:

1. This PR adds a new depency for just two tests
2. The `Unmarshal` method currently only supports exported fields of type `string` and `[]string`

But both can be resolved in a PR without breaking any functionality/backwards compatibility. I added further documentation and error checking when filling the struct fields, this also allows us to later add more supported field types.

**Pull request merged**
