### PR TITLE
Added search with channels first draft

### LINKED ISSUE #135: Return search results into channel
Currently all search results are returned when the call has finished, even for paged queries which can be quite huge results. Sending the results to a channel can be a great improvement in such cases where we can process the chunks right after they're received and do not have to wait for the last page to arrive.

Other search calls like a [persistent Search](https://www.ietf.org/proceedings/50/I-D/ldapext-psearch-03.txt) or [LDAP Sync](https://tools.ietf.org/html/rfc4533) will also benefit - these never end and need something to pass their results.

### PR DESCRIPTION
**Pull request by stefanmcshane**
Adapted #172 to be up to date with go mod

Fixes #135 

Marked as drafter as this is missing tests, and is currently only implemented in v3/ (go mods)
@dsheehan101 can you take a look? The example provided should work for testing against an LDAP server.

### CODE REVIEW

**Comment by stefanmcshane** [comment]
Need to further update SearchWithChannel to use #232 style requests

**Comment by xNevo** [comment]
Nice work! After looking through `v3/search.go`, this chunk stood out a bit:

```go
entry := new(Entry)
entry.DN = packet.Children[1].Children[0].Value.(string)
for _, child := range packet.Children[1].Children[1].Children {
	attr := new(EntryAttribute)
	attr.Name = child.Children[0].Value.(string)
	for _, value := range child.Children[1].Children {
		attr.Values = append(attr.Values, value.Value.(string))
		attr.ByteValues = append(attr.ByteValues, value.ByteValue)
	}
	entry.Attributes = append(entry.Attributes, attr)
}
```

Maybe that's just me, or this is completly out of scope for this PR, but for better readability maybe we should think about moving this chunk into it's own corresponding function? (Maybe we can even use make with a set length/capacity since we can determine the amount of attributes through the children anyways :) )

**Comment by xNevo** [comment]
I didn't do anything in Go for a ~2 months, but briefly put something together and run some benchmarks repeatly

```
attribute count (children per packet): 64
goos: windows
goarch: amd64
pkg: go-playground
cpu: Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
BenchmarkAttributesInline-4        22606             55768 ns/op           23033 B/op        455 allocs/op
BenchmarkAttributesFunc-4         58704             19540 ns/op           10752 B/op        129 allocs/op
```

I will continue to tinker with it over the next few days. If you want I can post my variant here. Please let me know what you think :)

**Comment by stefanmcshane** [comment]
@xNevo I totally agree, and thanks for the feedback. The idea in the draft was to get this working, then refactor for readability.
This is duplicated code from the [search function](https://github.com/go-ldap/ldap/blob/416b322e73ee5d05361acc052935d0605457b735/v3/search.go#L381). I think that when I have sufficiently tested the SearchWithChannel function, I will refactor Search to reduce the duplication.

If you want to make a PR with the benchmarks added in, we will welcome it!

**Comment by inv2004** [comment]
@stefanmcshane Any chance to move it from draft into master? It is important part or ldap at the moment

**Comment by michele-deluca** [comment]
Any news of this?

**Comment by t2y** [comment]
I heard this is related to #422. I might be able to help with something (refactoring, testing, etc.) if required.

**Comment by t2y** [comment]
I recreate a new PR including these changes. Could you review it?

* https://github.com/go-ldap/ldap/pull/440

**Pull request closed without merging**
