### PR TITLE
Add utf8 support to filter

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by johnweldon** [comment]
Thank you @BestianRU  and @liggitt

**Comment by BestianRU** [comment]
thank you for help and support :) I novice in the golang and github, but little by little study :) Without you, I would leave regexp version :)

**Comment by BestianRU** [comment]
can i delete go-ldap from my repository ?

**Comment by johnweldon** [comment]
yes, now that all your code is merged you can delete your fork (until you decide to contribute again, then you can fork again :) )

**Comment by BestianRU** [comment]
Ok, thank you :)

**Pull request merged**
