### PR TITLE
Update dependent packages:

### PR DESCRIPTION
**Pull request by iredmail**
- github.com/google/uuid v1.3.1
- golang.org/x/crypto v0.12.0

### CODE REVIEW

**Review by cpuschma — CHANGES_REQUESTED** [review]
Thank you for the PR. May you mirror the changes to the root directories go.mod and go.sum as well?

Additionally, I just checked and it seems, due to Go 1.21.0, that golang.org/x/crypto has been updated to v0.13.0. May you please run `go get -u ./...` again?

**Comment by iredmail** [comment]
According to current `v3/go.mod`, it requires Go 1.14, do we set it to 1.21.0 or stick to 1.14?

**Comment by cpuschma** [comment]
We stick with Go 1.14 unless it's necessary to drop support for it. In both this should be addressed in a separate PR

**Comment by iredmail** [comment]
hi @cpuschma,

Bumped crypto to v0.13.0, please help review and hopefully merge it. :)

**Comment by cpuschma** [comment]
Thank you. Can you update the deps for the root directories go.mod as well? Then we can merge it

**Comment by iredmail** [comment]
@cpuschma Done. :)

**Review by cpuschma — APPROVED** [review]

**Pull request merged**
