### PR TITLE
return search results via a channel

### LINKED ISSUE #135: Return search results into channel
Currently all search results are returned when the call has finished, even for paged queries which can be quite huge results. Sending the results to a channel can be a great improvement in such cases where we can process the chunks right after they're received and do not have to wait for the last page to arrive.

Other search calls like a [persistent Search](https://www.ietf.org/proceedings/50/I-D/ldapext-psearch-03.txt) or [LDAP Sync](https://tools.ietf.org/html/rfc4533) will also benefit - these never end and need something to pass their results.

### PR DESCRIPTION
**Pull request by vetinari**
fixes #135

### CODE REVIEW

**Comment by vetinari** [comment]
...and again 1.2 failing for no reason :(

**Comment by vetinari** [comment]
maybe we need to merge #171 first

**Comment by johnweldon** [comment]
@vetinari - wanna spruce this PR up and we can get it merged?

**Comment by johnweldon** [comment]
@vetinari any chance you want to update this PR?

**Pull request closed without merging**
