### PR TITLE
Use tls.DialWithDialer instead of net.DialTimeout

### PR DESCRIPTION
**Pull request by slene**
tls.DialWithDialer will auto create default tls.Config, such as ServerName

### CODE REVIEW

**Comment by liggitt** [comment]
Looks fine at first glance, though I need to make sure the behavior is identical across go versions

**Comment by liggitt** [comment]
can you rebase this on latest master? also, looks like tls.DialWithDialer is only available in go1.3+, so we'd need to wait until we up our supported go versions (c.f. https://github.com/go-ldap/ldap/issues/76)

**Comment by vitreuz** [comment]
Any update on this PR?

**Comment by liggitt** [comment]
still plan to pull it in as part of https://github.com/go-ldap/ldap/milestone/1, but don't have an eta for that yet

**Comment by liggitt** [comment]
included in #173

**Pull request closed without merging**
