### PR TITLE
DialURL supports options to configure net.Dialer and tls.Config

### PR DESCRIPTION
**Pull request by regeda**

### CODE REVIEW

**Comment by regeda** [comment]
The PR https://github.com/go-ldap/ldap/pull/209 might be closed after merge.

**Comment by stefanmcshane** [comment]
@regeda - As this is suggesting future deprecation of a feature, commits should be made in the v3 folder for Go Modules going forward. 
The top level code only exists whilst we figure out the best way to maintain backwards compatibility before Go Modules. 
TL:DR; please make changes to v3/ and I’ll review this weekend.

**Comment by regeda** [comment]
@stefanmcshane Unfortunately the subdirectory is not a good idea to fix `../v3` path because `go mod` takes the root folder anyway. For example, you could test it using `go mod vendor`.

From my perspective, we should do two things:
1. rename the module in `go.mod`:
```
module github.com/go-ldap/ldap
```
->
```
module github.com/go-ldap/ldap/v3
```
2. accept a savvy desicion and remove `v3` tag from the repo

**Comment by stefanmcshane** [comment]
As we were on v3 prior to Go Modules, updating a top level go.mod would have been considered a breaking change for backwards compatibility as outlined in #247. 
If you can get it working in such a way that does not break any old versions, we would be more than happy to review!
#246 for reference also

**Comment by regeda** [comment]
@stefanmcshane I have updated the code after your comments. Could you look at that?

**Comment by regeda** [comment]
@johnweldon Could you review the PR? Looks like it stucks.

**Comment by botastic** [comment]
Hey will there be a new realese / tag for this so I can get it without using the commit hash? :)

**Comment by johnweldon** [comment]
> Hey will there be a new realese / tag for this so I can get it without using the commit hash? :)

v3.1.4

**Comment by botastic** [comment]
Thank you very much

**Pull request merged**
