### PR TITLE
Export AddRequest Struct variables in add.go

### PR DESCRIPTION
**Pull request by nohupped**
wrote get methods to struct AddRequest in add.go, as the struct variables are not global, and it would be easy if an add request wants to be compared with another one before populating it.

### CODE REVIEW

**Comment by liggitt** [comment]
All the request structs except Add and Modify export their fields... I don't really see anything special about those that should be different. I think I'd be ok with just exporting DN and Attributes in `AddRequest`

**Comment by nohupped** [comment]
That's so kind of you, Thank you. I was wondering about modifying DN of the addrequest. One issue I faced was while comparing AD and LDAP add requests, where AD was returning realms like `"CN=abc,OU=xyz,DC=example,DC=com"` whereas LDAP was returning `"cn=abc,ou=xyz,dc=example,dc=com"` (uppercase/lowercase difference). If adding this feature is something redundant, which can be done using a `ModifyRequest`, I will follow that.

**Comment by liggitt** [comment]
that seems more like a normalization issue, not specific to add requests

**Comment by nohupped** [comment]
Gotcha, Thank you.

**Comment by nohupped** [comment]
@liggitt , Would you prefer to keep the get methods, or would you rather prefer to keep the struct fields exported with capital letter, just like in the del.go? I feel it would be better if you keep the struct fields exported with capital variable names, and users can add custom methods in their project based on their needs to modify the struct.

**Comment by nohupped** [comment]
@liggitt Would you prefer to keep the get methods, or keep the struct fields exported like `DN` and `Attributes`? My opinion is it would be great if you prefer to keep it exported in the latter way, as users will get the freedom to write methods to modify the original struct with their own wrapper structs in their projects as
```
type AddRequest struct {
	*ldap.AddRequest
}

func (a *AddRequest) SetDN(dn string) {
	a.DN = dn
}```

**Comment by liggitt** [comment]
yeah, I would just export the fields

**Comment by nohupped** [comment]
Thank you

**Comment by vetinari** [comment]
This is also in https://github.com/go-ldap/ldap/pull/49/commits/9b058acf1fe6a5ec2596483c4427637f9eb22485 (part of https://github.com/go-ldap/ldap/pull/49)

I need the exported ones to render the add / mod requests as LDIF

**Comment by nohupped** [comment]
I was wondering, if it would be fine to expose

    type Attribute struct {
        attrType string
        attrVals []string
    }

in `add.go` as well?

**Comment by liggitt** [comment]
I think it's ok to expose those, though I'd like to rename them to match the LDAP names before exposing them, so `Type` and `Vals`

**Comment by nohupped** [comment]
Hi @liggitt  I was wondering if this can be merged, as we are using a forked one for our project temporarily.

**Comment by liggitt** [comment]
@nohupped, merged, sorry for the delay
@vetinari, fyi, also broke out the change to export fields in ModifyRequest structs into #67 and merged that as well

**Comment by nohupped** [comment]
Thank you @liggitt

**Pull request merged**
