### PR TITLE
Add EqualFold function on AttributeTypeAndValue.

### PR DESCRIPTION
**Pull request by zerodayz**
Since v3 ldap we have case insensitive search in parallel to a case sensitive search:

https://github.com/go-ldap/ldap/pull/111

I would like to propose to add an EqualFold function in parallel to Equal function in dn.go on AttributeTypeAndValue.

So we can not only search in case sensitive but also compare RDNs.

### CODE REVIEW

**Comment by zerodayz** [comment]
I can't seem to find specific RFC where it would say otherwise, but working with Active Directory in the past it didn't allow to have ou=Groups and ou=groups at the same time. So wondering why only the type has been considered but not the value itself.

**Comment by zerodayz** [comment]
@liggitt @johnweldon We already have a search that is case sensitive (since v3) and would be beneficial if we can also have RND compare functions as case insensitive.

**Comment by stefanmcshane** [comment]
Hi @zerodayz, please apply the changes to v3/ folder's relevant files and rebase so we can consider merging.

Ill review this weekend to get a new release out this week then.

Thanks,
Stefan

**Comment by zerodayz** [comment]
Hi @stefanmcshane, applied changes to v3 directory. Thank you Stefan

**Comment by stefanmcshane** [comment]
Hi @zerodayz, 
The latest commit seems to have removed the changes from the project root. Whilst it is a little confusing, we are currently supporting 2 versions of the ldap library in 1 repo.
The code inside `v3/` folder is what gets pulled when running with go modules, and the code at the project root is what gets pulled when working without go modules. As such, if you could ensure the changes are in both `v3/dn.go` and `dn.go`, that would ensure the 2 versions are in sync.
We have plans to deprecated support for no-go module version in the not-too-distant future to avoid this confusion.

Thanks for your help and contribution,
Stefan

**Comment by zerodayz** [comment]
@stefanmcshane I have added those back into root.

**Comment by stefanmcshane** [comment]
Merged this - If you get a chance to write some supporting unit tests, those would be greatly appreciated.

**Pull request merged**
