### PR TITLE
Allow tests to work with github.com or gopkg.in clones

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by johnweldon** [comment]
I thought I'd run into issues with using dot imports, but since this is just in the tests, and it seems to work fine... LGTM

**Comment by liggitt** [comment]
hold off on merging... still getting travis happy

**Comment by liggitt** [comment]
wondering if we should just make the unit test files be in the same package

**Comment by liggitt** [comment]
I'm sort of at a loss how to make travis/master tests run well from a clone that maps to the v2 branch through gopkg.in... I haven't seen much discussion of this anywhere.

**Comment by johnweldon** [comment]
yeah; gopkg.in has been less useful to me than I expected.

I'll try ask Gustavo if he has any recommendations for running tests from different contexts

**Comment by johnweldon** [comment]
Sent an email; I expect the response, if any, will be: "Don't do that"

**Pull request closed without merging**
