### PR TITLE
Update godoc, add gofmt check

### PR DESCRIPTION
**Pull request by liggitt**
Get clean gofmt/govet/golint checks, add makefile and pre-push hook to simplify running checks, invoke checks in travis

### CODE REVIEW

**Comment by liggitt** [comment]
@johnweldon any preference on the location/names of the verify scripts?

**Comment by johnweldon** [comment]
@liggitt I usually have a scripts folder with verify.sh that does the go fmt check and the go vet check, and then a pre-push.sh that wraps that, and is used for the git pre-push hook.

**Comment by liggitt** [comment]
@johnweldon after playing with scripts for a while, I think I like a makefile better... lets you do things like this:
```
# runs all default tasks
make
# just run tests
make test
# just run linting
make lint
...
```

**Comment by johnweldon** [comment]
@liggitt I'm great with Makefile too - agree it can be useful for different targets or conditional targets

**Pull request merged**
